sudo: required
dist: focal

os: linux

branches:
  only:
    - "master"
language: c

addons:
  apt:
    packages:
    - axel
    - cpanminus
    - libtest-base-perl
    - libtext-diff-perl
    - liburi-perl
    - libwww-perl
    - libtest-longstring-perl
    - liblist-moreutils-perl
    - libgd-dev
  postgresql: "13"

cache:
  apt: true
  directories:
  - download-cache

compiler:
  - gcc

env:
  global:
    - LUAJIT_PREFIX=/opt/luajit21
    - LUAJIT_LIB=$LUAJIT_PREFIX/lib
    - LD_LIBRARY_PATH=$LUAJIT_LIB:$LD_LIBRARY_PATH
    - LUAJIT_INC=$LUAJIT_PREFIX/include/luajit-2.1
    - LUA_INCLUDE_DIR=$LUAJIT_INC
    - LUA_CMODULE_DIR=/lib
    - JOBS=3
    - DRIZZLE_VER=2011.07.21
    - NGX_BUILD_JOBS=$JOBS
    - TEST_NGINX_SLEEP=0.006
  matrix:
    - NGINX_VERSION=1.25.1 NGX_EXTRA_OPT=--without-pcre2

services:
 - mysql
 - postgresql

install:
  - if [ ! -f download-cache/drizzle7-$DRIZZLE_VER.tar.gz ]; then wget -P download-cache https://github.com/openresty/openresty-deps-prebuild/releases/download/v20230902/drizzle7-$DRIZZLE_VER.tar.gz; fi
  - git clone https://github.com/openresty/openresty-devel-utils.git
  - git clone https://github.com/openresty/openresty.git ../openresty
  - git clone https://github.com/openresty/no-pool-nginx.git ../no-pool-nginx
  - git clone https://github.com/simpl/ngx_devel_kit.git ../ndk-nginx-module
  - git clone https://github.com/openresty/test-nginx.git
  - git clone -b v2.1-agentzh https://github.com/openresty/luajit2.git
  - git clone https://github.com/openresty/lua-nginx-module.git ../lua-nginx-module
  - git clone https://github.com/openresty/lua-resty-core.git ../lua-resty-core
  - git clone https://github.com/openresty/lua-resty-lrucache.git ../lua-resty-lrucache
  - git clone https://github.com/openresty/echo-nginx-module.git ../echo-nginx-module
  - git clone https://github.com/openresty/nginx-eval-module.git ../eval-nginx-module
  - git clone https://github.com/openresty/xss-nginx-module.git ../xss-nginx-module
  - git clone https://github.com/openresty/set-misc-nginx-module.git ../set-misc-nginx-module
  - git clone https://github.com/openresty/array-var-nginx-module.git ../array-var-nginx-module
  - git clone https://github.com/openresty/drizzle-nginx-module.git ../drizzle-nginx-module
  - git clone https://github.com/calio/form-input-nginx-module.git ../form-input-nginx-module
  - git clone https://github.com/openresty/ngx_postgres.git ../postgres-nginx-module
  - git clone https://github.com/openresty/openresty.git ../ngx_openresty

before_script:
  - mysql -uroot -e "create database ngx_test; CREATE USER 'ngx_test'@'%' IDENTIFIED WITH mysql_native_password BY 'ngx_test'; grant all on ngx_test.* to 'ngx_test'@'%'; flush privileges;"
  - mysql -uroot -e 'alter database ngx_test character set utf8mb4 collate utf8mb4_unicode_ci;'
  - psql -c "create database ngx_test;" -U postgres
  - psql -c "create user ngx_test with password 'ngx_test';" -U postgres
  - psql -c "grant all privileges on database ngx_test to ngx_test;" -U postgres

script:
  - tar xzf download-cache/drizzle7-2011.07.21.tar.gz && cd drizzle7-2011.07.21
  - ./configure --prefix=/usr --without-server > build.log 2>&1 || (cat build.log && exit 1)
  - sudo PATH=$PATH make libdrizzle-1.0 install-libdrizzle-1.0 > build.log 2>&1 || (cat build.log && exit 1)
  - cd ../luajit2
  - make -j$JOBS CCDEBUG=-g Q= PREFIX=$LUAJIT_PREFIX CC=$CC XCFLAGS='-DLUA_USE_APICHECK -DLUA_USE_ASSERT' > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make install PREFIX=$LUAJIT_PREFIX > build.log 2>&1 || (cat build.log && exit 1)
  - cd ../test-nginx && sudo cpanm . && cd ..
  - export PATH=$PWD/work/nginx/sbin:$PWD/openresty-devel-utils:$PATH
  - export NGX_BUILD_CC=$CC
  - sh util/build.sh $NGINX_VERSION > build.log 2>&1 || (cat build.log && exit 1)
  - nginx -V
  - prove -I. -r t
